---
title: Teacher Movies
date: 2023-08-29T08:36:17-04:00
tags:
- education
categories:
- education
draft: false
--- 

It's back to school time and in addition to all the usual back to
school angst and excitement it's also time for the networks to stream
all those teacher movies.

Lots of a-list actors have been in teacher movies and many are really
entertaining but I've also found many of them to be problematic.

It's not because many of them are "white savior" films, even though,
yeah, that too, but rather because many are indirectly demeaning to
teachers and the teaching profession in general.

The typical trope is non teacher with no teaching background gets job
in hard school. Teacher struggles. Amazingly, teacher with no
background wins over their students and performs miracles. Many of
these movies are "based on a true story."

Other highlighted tropes are:

1. None of the experienced career teachers are any good. Their all
   horrible by every account.
2. The administrations are also similarly bad. 
3. As a result, the teacher rescues their class all by themselves.

Also interesting is that the star teacher in all the movies only ever
seems to teach one class.

Another interesting thing is that when reading the movie post-text or
looking up the teacher afterwards, they almost invariably left
education soon after - frequently it seems to cash in on the fame
resulting from the movie.

If you think about it, this sends a horrible message - well prepared,
trained, dedicated teachers are all bad. No administrators care for
the students and it takes these miracle workers to swoop in.

Nonsense - education is hard and is the long game and just like every
profession - there are a few stars and a few rotten apples and bunch
of hard working solid professionals in between.

Another truth is that, at least in the few instances I know of, where
there was a success it was actually with the support of other teachers
and/or the administration.

My first exposure to this was from "Small Victories." A book - never
made into a movie. It focused on a teacher at Seward Park High School
and was published right before I started there (my first teaching
gig). It wasn't a miracle story but focused on how the teacher in
question embraced the students with challenges and they found many
"small victories" helping these students in their lives. The teacher,
Jessica Siegel was in her 10th year teaching which is pretty good but
she left soon after the book came out - right before I came on
board. The book mentioned many other teachers but the focus was on
her. The reality was that it was much more of a team effort. I got to
know many of the players briefly mentioned in the book and indeed I
can see that was the truth. Honestly, though, I don't want to detract
from Jessica Siegel's work there - my best guess it was an ensemble
effort in the school but as expected the author felt he had to focus on
somebody.

The next was "Stand and Deliver" with Edward James Olmos as Jaome
Escalante - the miracle teacher who overcame a school full of
loser teachers. From what I was told by teachers with more of an
inside view was that while Mr. Escalante did some great stuff it was a
team effort. Makes for a better story but it demeans the rest of the
hard working teachers in the school. I'm reminded of a piece a read
about how Dan Devine - the former Notre Dame coach was hurt when he
saw how he was portrayed in the movie "Rudy." He was made the heavy
who was going to deny Rudy his shot. The reality was apparently
otherwise with Dan Devine being rather supportive.

Escalante and Siegel differ from many of the other miracle teacher
stories in that they both taught for at least 10 years. 

Of course, not all teacher movies are bad and even the bad ones can be
entertaining and many were created as fiction and are not based on a
true story.

* Here are some that have school elements that I like:

** Lean on me

Based on Joe Clark - a no excuses principal in New Jersey. I'm not
particularly a Joe Clark fan but there were a number of things I liked
about the movie.

- It showed both supportive and antagonistic parents, administrators,
  and influences.

- By the end, Joe Clark acknowledged that he needed and appreciated the
  hard work and dedication of his staff.

- It highlighted how educators are frequently between a rock and a
  hard place - you've got to keep the drug dealers out but you can't
  lock the doors.

Again, not a Joe Clark fan but if you pay attention there's some good
balance here and it's early Morgan Friedman so that's always a plus.

** To Sir with Love

I mean, Sidney Poitier so that's enough reason to watch. It's
interesting because it's kindof a reverse "White Savior" story with
Poitier being black and his class mostly poor white. It's got plenty
of faults - he only appears to teach one class and he never does
anything academic but it's got good balance. There's a bad teacher
who's the heavy but there are also good supportive teachers and
administrators. Poitier faces real challenges and even loses his cool,
gets advice from other teachers and finds his way.

This is a good one.

** Dead Poets Society

I mention this as an aside. I think it's interesting because the
teacher in question Kohn Keating comes in with credentials. He also
isn't saving the students in the same sense - I mean it is an elite
private boarding school. The other educators are a mixed bag and
that's realistic and I think the description of the school is
reasonably accurate given the time and place.

* And maybe my favorite

One of the best teacher movies and a great one to watch at this time
of years is "Mr. Holland's Opus." Richard Dreyfuss, Olympia Dukakis,
and others. Frustrated musician takes a teaching job to pay the bills
and indeed becomes that influential teacher. Never shown as the super
charismatic miracle worker but a dedicated pro who would do anything
to reach his students and help them to love music. It's a movie about
any of us, all of us who've pushed through the decades to work for our
students without the limelight but in the end, as Mr Holland got to
see, made a great difference in many lives.


So, as the school year starts, enjoy the teacher movies - the good,
the bad, and the fun.


